### ISSUE TITLE
Cast exception on onSaveInstanceState and onRestoreInstanceState

### ISSUE THREAD

**Issue by sapuglha** [GuilhE/android-seekbar-ranged-view#5]
I have a screen with the component, rotate it and there is this exception.

```
W/Bundle: Attempt to cast generated internal exception:
    java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.Float
        at android.os.BaseBundle.getFloat(BaseBundle.java:1104)
        at android.os.Bundle.getFloat(Bundle.java:834)
        at android.os.BaseBundle.getFloat(BaseBundle.java:1086)
        at android.os.Bundle.getFloat(Bundle.java:821)
        at com.github.guilhe.rangeseekbar.SeekBarRangedView.onRestoreInstanceState(SeekBarRangedView.java:834)
        at android.view.View.dispatchRestoreInstanceState(View.java:18608)
        at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3827)
        at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3827)
        at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3827)
        at android.view.View.restoreHierarchyState(View.java:18586)
        at androidx.fragment.app.Fragment.restoreViewState(Fragment.java:576)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1349)
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1686)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1750)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3074)
        at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:3028)
        at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:2693)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1346)
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1686)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1750)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3074)
        at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:3028)
        at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:247)
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:541)
        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:201)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1391)
        at android.app.Activity.performStart(Activity.java:7157)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:2937)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

W/Bundle: Key MAX expected Float but value was a java.lang.Double.  The default value 0.0 was returned.
W/Bundle: Attempt to cast generated internal exception:
    java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.Float
        at android.os.BaseBundle.getFloat(BaseBundle.java:1104)
        at android.os.Bundle.getFloat(Bundle.java:834)
        at android.os.BaseBundle.getFloat(BaseBundle.java:1086)
        at android.os.Bundle.getFloat(Bundle.java:821)
        at com.github.guilhe.rangeseekbar.SeekBarRangedView.onRestoreInstanceState(SeekBarRangedView.java:835)
        at android.view.View.dispatchRestoreInstanceState(View.java:18608)
        at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3827)
        at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3827)
        at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3827)
        at android.view.View.restoreHierarchyState(View.java:18586)
        at androidx.fragment.app.Fragment.restoreViewState(Fragment.java:576)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1349)
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1686)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1750)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3074)
        at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:3028)
        at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:2693)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1346)
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1686)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1750)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3074)
        at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:3028)
        at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:247)
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:541)
        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:201)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1391)
        at android.app.Activity.performStart(Activity.java:7157)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:2937)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

The block of code saves a double and tries to restore a float. Shouldn't it be the same type on save and on restore?

```
    @Override
    protected Parcelable onSaveInstanceState() {
        final Bundle bundle = new Bundle();
        bundle.putParcelable("SUPER", super.onSaveInstanceState());
        bundle.putDouble("MIN", mNormalizedMinValue);
        bundle.putDouble("MAX", mNormalizedMaxValue);
        return bundle;
    }

    @Override
    protected void onRestoreInstanceState(Parcelable parcel) {
        final Bundle bundle = (Bundle) parcel;
        super.onRestoreInstanceState(bundle.getParcelable("SUPER"));
        mNormalizedMinValue = bundle.getFloat("MIN");
        mNormalizedMaxValue = bundle.getFloat("MAX");
        onChangedValues();
        onChangingValues();
    }
```

**Comment by GuilhE** [comment]
Hi Tiago,
Nice catch! New version coming up to fix this issue, let's wait till **maven** syncs :)

Thanks.
